export const LOAD_HISTORY_LOADING = 'LOAD_HISTORY_LOADING';
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS';
export const LOAD_HISTORY_ERROR = 'LOAD_HISTORY_ERROR';

export const LOAD_LAUNCHES_LOADING = 'LOAD_LAUNCHES_LOADING';
export const LOAD_LAUNCHES_SUCCESS = 'LOAD_LAUNCHES_SUCCESS';
export const LOAD_LAUNCHES_ERROR = 'LOAD_LAUNCHES_ERROR';
