export const LOAD_HISTORY_REQUEST = 'LOAD_HISTORY_REQUEST';
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS';
export const LOAD_HISTORY_ERROR = 'LOAD_HISTORY_ERROR';

export const LOAD_LAUNCHES_REQUEST = 'LOAD_LAUNCHES_REQUEST';
export const LOAD_LAUNCHES_SUCCESS = 'LOAD_LAUNCHES_SUCCESS';
export const LOAD_LAUNCHES_ERROR = 'LOAD_LAUNCHES_ERROR';
export const FILTER_MISSION_NAME = 'FILTER_MISSION_NAME';
export const FILTER_MISSION_DATE_FROM = 'FILTER_MISSION_DATE_FROM';
export const FILTER_MISSION_DATE_TO = 'FILTER_MISSION_DATE_TO';

export const LOAD_ROCKETS_REQUEST = 'LOAD_ROCKETS_REQUEST';
export const LOAD_ROCKETS_SUCCESS = 'LOAD_ROCKETS_SUCCESS';
export const LOAD_ROCKETS_ERROR = 'LOAD_ROCKETS_ERROR';
export const FILTER_ORBIT = 'FILTER_ORBIT';
